application: latexchat
version: 2
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /images
  static_dir: images
- url: /.*
  script: latexchat.py


builtins:
- datastore_admin: on